name: CI
on:
  push:
    branches:
  pull_request:
env:
  GCLOUD_CREDENTIAL_BASE64: ${{ secrets.GCLOUD_CREDENTIAL_BASE64 }}
  # Remove "-dev" only in a release branch.
  RELEASE_VERSION: 0.1.0
  ASSET_NAME_PREFIX: savetailor-external-
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steffenl/cxx-builder:1.2
      volumes:
        - /node20_glibc2.17:/node20_glibc2.17:rw,rshared
        - /node20_glibc2.17:/__e/node20:ro,rshared
    strategy:
      matrix:
        build-type: [Debug, Release]
        library-type: [static, shared]
    steps:
      - name: Install Node.js 20 for glibc 2.17
        run: |
          apt-get install -y curl
          filename=node-v20.9.0-linux-x64-glibc-217.tar.xz
          sha256_digest=60342b998325c2fa812741c4618374e039c54c4eab942032a028f08649debb23
          curl -sSLO "https://unofficial-builds.nodejs.org/download/release/v20.9.0/${filename}"
          echo "${sha256_digest} *${filename}" | sha256sum -c -
          tar -xf "${filename}" --strip-components 1 -C /node20_glibc2.17
          ldd /__e/node20/bin/node
      - uses: actions/checkout@v4
      - name: Build
        env:
          GCLOUD_BUCKET: ${{ vars.GCLOUD_BUCKET }}
          CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r scripts/requirements.txt
          export BUILD_SHARED_LIBS=$(echo '${{ matrix.library-type }}' | sed 's/static/OFF/' | sed 's/shared/ON/')
          export INSTALL_DIR="${PWD}/install"
          python3 scripts/devenv.py python3 scripts/build.py
        shell: bash
      - name: Create package
        run: |
          mkdir dist
          echo "${{ github.sha }}" > install/version.txt
          os=$(echo '${{ runner.os }}' | tr '[:upper:]' '[:lower:]')
          arch=$((if [[ "${OSTYPE}" =~ cygwin|msys ]]; then echo "${PROCESSOR_ARCHITECTURE}"; else uname --machine; fi) | tr '[:upper:]' '[:lower:]')
          build_type=$(echo '${{ matrix.build-type }}' | tr '[:upper:]' '[:lower:]')
          library_type="${{ matrix.library-type }}"
          (cd install && tar --create --xz "--file=../dist/${ASSET_NAME_PREFIX}${RELEASE_VERSION}-${os}.${arch}.${library_type}.${build_type}.tar.xz" *)
        shell: bash
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: dist-${{ runner.os }}-${{ matrix.build-type }}-${{ matrix.library-type }}
          path: dist/*
          retention-days: 1
  build-windows:
    runs-on: windows-2025
    strategy:
      matrix:
        build-type: [Debug, Release]
        library-type: [static, shared]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          GCLOUD_BUCKET: ${{ vars.GCLOUD_BUCKET }}
          CMAKE_BUILD_TYPE: ${{ matrix.build-type }}
        run: |
          python3 -m venv .venv
          source .venv/Scripts/activate
          pip install -r scripts/requirements.txt
          export BUILD_SHARED_LIBS=$(echo '${{ matrix.library-type }}' | sed 's/static/OFF/' | sed 's/shared/ON/')
          export INSTALL_DIR="${PWD}/install"
          python3 scripts/devenv.py python3 scripts/build.py
        shell: bash
      - name: Create package
        run: |
          mkdir dist
          echo "${{ github.sha }}" > install/version.txt
          os=$(echo '${{ runner.os }}' | tr '[:upper:]' '[:lower:]')
          arch=$((if [[ "${OSTYPE}" =~ cygwin|msys ]]; then echo "${PROCESSOR_ARCHITECTURE}"; else uname --machine; fi) | tr '[:upper:]' '[:lower:]')
          build_type=$(echo '${{ matrix.build-type }}' | tr '[:upper:]' '[:lower:]')
          library_type="${{ matrix.library-type }}"
          (cd install && tar --create --xz "--file=../dist/${ASSET_NAME_PREFIX}${RELEASE_VERSION}-${os}.${arch}.${library_type}.${build_type}.tar.xz" *)
        shell: bash
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: dist-${{ runner.os }}-${{ matrix.build-type }}-${{ matrix.library-type }}
          path: dist/*
          retention-days: 1
  publish:
    needs:
      - build-linux
      - build-windows
    if: github.event_name == 'push' && github.ref_type == 'branch' && startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist*
          path: dist
          merge-multiple: true
      - name: List artifacts
        run: find dist/
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --draft --target "${{ github.sha }}" "v${RELEASE_VERSION}" dist/*
        shell: bash
